[package]
name = "gpt-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
env_logger = "0.11"
anyhow = "1.0"
candle-core = { version = "0.9" }
candle-nn = "0.9"
candle-transformers = "0.9"
rand = "0.8"